<?php

/**
 * @file
 * Adds BigPipe no-JS detection.
 */

use Drupal\big_pipe\Render\Placeholder\BigPipeStrategy;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 *
 * @see \Drupal\big_pipe\Controller\BigPipeController::setNoJsCookie()
 */
function big_pipe_page_attachments(array &$page) {
  $request = \Drupal::request();
  // BigPipe is only used when there is an actual session, so only add the no-JS
  // detection when there actually is a session.
  // @see \Drupal\big_pipe\Render\Placeholder\BigPipeStrategy.
  $session_exists = \Drupal::service('session_configuration')->hasSession($request);
  $page['#cache']['contexts'][] = 'session.exists';
  // Only do the no-JS detection while we don't know if there's no JS support:
  // avoid endless redirect loops.
  $has_big_pipe_nojs_cookie = $request->cookies->has(BigPipeStrategy::NOJS_COOKIE);
  $page['#cache']['contexts'][] = 'cookies:' . BigPipeStrategy::NOJS_COOKIE;
  if ($session_exists && !$has_big_pipe_nojs_cookie) {
    $page['#attached']['html_head'][] = [
      [
        // Redirect through a 'Refresh' meta tag if JavaScript is disabled.
        '#tag' => 'meta',
        '#noscript' => TRUE,
        '#attributes' => [
          'http-equiv' => 'Refresh',
          'content' => '0; URL=' . Url::fromRoute('big_pipe.nojs', [], ['query' => \Drupal::service('redirect.destination')->getAsArray()])->toString(),
        ],
      ],
      'big_pipe_detect_nojs',
    ];
  }
}
