<?php

function bfc_admin_theme_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);
  if ($path_args[1] == 'user' and ($path_args[2] == 'login')) {
    $variables['attributes']['class'][]= 'path-user-login';
  }
}

function bfc_admin_theme_preprocess_install_page(&$variables) {
  $info = system_get_info('module', 'system');
  $variables['drupal_version'] = $info['version'];
}
