# Schema for the configuration files of the Logout tab module.

logouttab.settings:
  type: config_object
  label: 'Logout tab settings'
  mapping:
    url:
      type: string
      label: 'URL for the account logout page'
    weight:
      type: integer
      label: 'Weight of the tab'
